# Generated by Django 5.2.6 on 2025-09-12 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_delete_subject'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='admins.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='teachers.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subject_assignments', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('group', 'subject')},
            },
        ),
    ]
