# Generated by Django 5.2.6 on 2025-09-12 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_groupsubjectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='admins.degree'),
        ),
    ]
